# Generated by Django 6.0.6 on 2026-09-21 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('CONSUMER', 'Consumer'), ('BULK', 'Bulk')], default='CONSUMER', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('FARMER_MATCHED', 'Farmer Matched'), ('HARVEST_SCHEDULED', 'Harvest Scheduled'), ('PICKUP_ASSIGNED', 'Pickup Assigned'), ('PRODUCE_COLLECTED', 'Produce Collected'), ('AT_COLLECTION_CENTER', 'At Collection Center'), ('QUALITY_CHECKED', 'Quality Checked'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Farmer base total', max_digits=10)),
                ('collection_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_address', models.TextField()),
                ('delivery_city', models.CharField(default='Pune', max_length=100)),
                ('delivery_slot', models.CharField(default='05:00 PM – 07:00 PM', max_length=100)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_date', models.CharField(max_length=50)),
                ('actual_harvest_date', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('READY', 'Ready for Harvest'), ('HARVESTED', 'Harvested'), ('COLLECTED', 'Collected')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to=settings.AUTH_USER_MODEL)),
                ('produce_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='products.producelisting')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerOrderAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confirmed_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('READY', 'Ready for Harvest'), ('PICKED_UP', 'Picked Up'), ('AT_CENTER', 'At Collection Center')], default='MATCHED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_allocations', to=settings.AUTH_USER_MODEL)),
                ('produce_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producelisting')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Locked historical purchase rate', max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_order_items', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('produce_listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.producelisting')),
            ],
        ),
    ]
