# Generated by Django 6.0.6 on 2026-09-21 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains & Pulses', 'Grains & Pulses'), ('Commercial Crops', 'Commercial Crops'), ('Spices', 'Spices')], default='Vegetables', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variety', models.CharField(blank=True, default='', max_length=150)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_unit', models.CharField(default='kg', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='₹ per unit set by farmer', max_digits=8)),
                ('market_ref_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ai_suggested_min', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ai_suggested_max', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quality_grade', models.CharField(choices=[('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Grade C', 'Grade C')], default='Grade A', max_length=20)),
                ('harvest_date', models.CharField(help_text='e.g. 25 Sept or YYYY-MM-DD', max_length=50)),
                ('harvest_status', models.CharField(choices=[('Growing', 'Growing'), ('Ready for Harvest', 'Ready for Harvest'), ('Harvested', 'Harvested'), ('Pickup Scheduled', 'Pickup Scheduled'), ('Collected', 'Collected')], default='Growing', max_length=30)),
                ('location', models.CharField(default='Sangli', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('organic', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PARTIALLY_SOLD', 'Partially Sold'), ('SOLD_OUT', 'Sold Out'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product')),
            ],
        ),
    ]
