# Generated by Django 6.0.6 on 2026-09-21 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('region', models.CharField(default='Western Maharashtra', max_length=100)),
                ('time_horizon', models.CharField(default='7_day', max_length=50)),
                ('predicted_demand_kg', models.DecimalField(decimal_places=2, default=12500, max_digits=12)),
                ('available_supply_kg', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('demand_status', models.CharField(default='High', max_length=50)),
                ('warning_message', models.TextField(blank=True, default='')),
                ('ai_explanation', models.TextField(blank=True, default='')),
                ('historical_data', models.JSONField(default=list)),
                ('seven_day_forecast', models.JSONField(default=list)),
                ('thirty_day_forecast', models.JSONField(default=list)),
                ('disclaimer', models.CharField(default='AI provides demand estimations based on historical sales and seasonal trends. Actual demand may vary.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=100)),
                ('market_ref_price', models.DecimalField(decimal_places=2, default=23, max_digits=10)),
                ('suggested_min', models.DecimalField(decimal_places=2, default=22, max_digits=10)),
                ('suggested_max', models.DecimalField(decimal_places=2, default=26, max_digits=10)),
                ('quality_grade', models.CharField(default='Grade A', max_length=20)),
                ('logistics_cost_per_kg', models.DecimalField(decimal_places=2, default=3, max_digits=6)),
                ('handling_cost_per_kg', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('platform_fee_per_kg', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.92, max_digits=4)),
                ('explanation', models.TextField(default='Price calibrated from regional Mandi arrivals, festive index, and forward retail orders.')),
                ('disclaimer', models.CharField(default='AI provides a recommendation. The farmer decides the final selling price.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
