# Generated by Django 6.0.6 on 2026-09-21 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Damaged produce', 'Damaged produce'), ('Late delivery', 'Late delivery'), ('Wrong quantity', 'Wrong quantity'), ('Quality mismatch', 'Quality mismatch'), ('Payment issue', 'Payment issue'), ('Other', 'Other')], default='Damaged produce', max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='orders.order')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_complaints', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
