# Generated by Django 6.0.6 on 2026-09-21 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_centers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_number', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(default='Sangli Agro Collection Hub #4', max_length=255)),
                ('destination', models.TextField(default='Kothrud, Pune')),
                ('scheduled_time', models.CharField(default='05:00 PM – 07:00 PM', max_length=50)),
                ('estimated_time', models.CharField(default='06:15 PM', max_length=50)),
                ('actual_delivery_time', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='OUT_FOR_DELIVERY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_km', models.DecimalField(decimal_places=2, default=42.0, max_digits=6)),
                ('estimated_duration', models.CharField(default='1 hr 35 min', max_length=50)),
                ('route_data', models.JSONField(default=dict)),
                ('is_optimal_claimed', models.BooleanField(default=False, help_text='Disclaim absolute optimality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='logistics.delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(default='MH-10-AB-1234', max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Pickup Truck (1 Ton)', 'Pickup Truck (1 Ton)'), ('Refrigerated Van (1.5 Ton)', 'Refrigerated Van (1.5 Ton)'), ('Mini Cargo (750 kg)', 'Mini Cargo (750 kg)'), ('Medium Truck (3 Ton)', 'Medium Truck (3 Ton)'), ('Electric Cargo (1 Ton)', 'Electric Cargo (1 Ton)')], default='Pickup Truck (1 Ton)', max_length=50)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=1000, max_digits=8)),
                ('current_load_kg', models.DecimalField(decimal_places=2, default=750, max_digits=8)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_location_name', models.CharField(default='Miraj Ring Road, Sangli', max_length=255)),
                ('status', models.CharField(choices=[('Available for pickup', 'Available for pickup'), ('On Pickup Route', 'On Pickup Route'), ('Loaded', 'Loaded'), ('In Transit to Hub', 'In Transit to Hub'), ('Delivering', 'Delivering'), ('Maintenance', 'Maintenance')], default='Available for pickup', max_length=30)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_number', models.CharField(max_length=50, unique=True)),
                ('scheduled_date', models.CharField(default='Today', max_length=50)),
                ('scheduled_time', models.CharField(default='07:30 AM – 08:30 AM', max_length=50)),
                ('pickup_address', models.TextField(default='Miraj Farm Plot #14, Sangli')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=300, max_digits=8)),
                ('proof_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('PICKED_UP', 'Picked Up'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_centers.collectioncenter')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_pickups', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to=settings.AUTH_USER_MODEL)),
                ('harvest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='orders.harvest')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle'),
        ),
    ]
