# Generated by Django 6.0.6 on 2026-09-21 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('district', models.CharField(default='Sangli', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, default=15000, help_text='kg', max_digits=10)),
                ('current_capacity', models.DecimalField(decimal_places=2, default=8400, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FULL', 'Full')], default='ACTIVE', max_length=20)),
                ('contact_phone', models.CharField(default='+91 97630 11980', max_length=20)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_centers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actual_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FLAGGED', 'Flagged')], default='VERIFIED', max_length=20)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='collection_centers.collectioncenter')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_receipts', to=settings.AUTH_USER_MODEL)),
                ('harvest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.harvest')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProduceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(default='Grade A', max_length=20)),
                ('status', models.CharField(choices=[('SORTED', 'Sorted'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched')], default='PACKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='collection_centers.collectioncenter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality_grade', models.CharField(choices=[('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Grade C', 'Grade C'), ('REJECTED', 'Rejected')], default='Grade A', max_length=20)),
                ('quality_score', models.DecimalField(decimal_places=2, default=95.0, help_text='Out of 100', max_digits=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('collection_receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='collection_centers.collectionreceipt')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
